name: Build and Push Image

on:
  push:
    branches: 
     - main
     - feature/*
  pull_request:
    branches: 
      - main
      - feature/* 
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub environment to use (controls secrets/approvals)"
        type: choice
        required: true
        default: staging
        options:
          - staging
          - production


env:
  PRIMARY_REGION: eu-west-1
  SECONDARY_REGION: us-east-1
  REPOSITORY: gorilla-clinic

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.PRIMARY_REGION }}


      - name: Login to Amazon ECR (Primary)
        run: |
          aws ecr get-login-password --region ${{ env.PRIMARY_REGION }} | \
            docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.PRIMARY_REGION }}.amazonaws.com

      - name: Login to Amazon ECR (Secondary)
        run: |
          aws ecr get-login-password --region ${{ env.SECONDARY_REGION }} | \
            docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.SECONDARY_REGION }}.amazonaws.com

      - name: Build Image
        run: |
          PRIMARY_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.PRIMARY_REGION }}.amazonaws.com/${{ env.REPOSITORY }}
          SECONDARY_IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.SECONDARY_REGION }}.amazonaws.com/${{ env.REPOSITORY }}
          echo "PRIMARY_IMAGE=$PRIMARY_IMAGE" >> $GITHUB_ENV
          echo "SECONDARY_IMAGE=$SECONDARY_IMAGE" >> $GITHUB_ENV
          echo "Building image tagged as:"
          echo "  $PRIMARY_IMAGE:cat"
          echo "  $SECONDARY_IMAGE:cat"
          docker buildx build \
            --platform linux/amd64 \
            --load \
            -t $PRIMARY_IMAGE:cat \
            -t $SECONDARY_IMAGE:cat \
            .

      - name: Push Image (Primary)
        run: |
          docker push $PRIMARY_IMAGE:cat

      - name: Push Image (Secondary)
        run: |
          docker push $SECONDARY_IMAGE:cat

