
# name: Notify Infra Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   dispatch:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Trigger infra repository_dispatch
#         uses: peter-evans/repository-dispatch@v3
#         with:
#           token: ${{ secrets.INFRA_REPO_TOKEN }}
#           repository: ${{ secrets.INFRA_REPO_FULL_NAME }}
#           event-type: app-repo-update
#           client-payload: |
#             {
#               "triggered_by": "${{ github.repository }}",
#               "sha": "${{ github.sha }}",
#               "ref": "${{ github.ref }}",
#               "workflow": "${{ github.workflow }}",
#               "event_name": "${{ github.event_name }}",
#               "run_id": "${{ github.run_id }}"
#             }

